# reference file configuration
FASTA: 
INDEX: 

#True or False
DEDUPLICATE: True

CHRFILE: chr_len.txt
VCFJOBS: 50
# sample
samples: samples.tsv
depth: 20
PLOIDY: 2

# annotation
Annotation: False
snpEff: /opt/biosoft/snpEff/snpEff.jar
SnpEffDB: Arabidopsis_thaliana